### ISSUE TITLE
Rename "Technologies" section in README to "Software Stack"

### ISSUE THREAD

**Issue by jleung51** [jleung51-coursework/phaser#29]
The term slipped my mind when I wrote the README and it wasn't until recently that I remembered it. [Software stack](https://en.wikipedia.org/wiki/Solution_stack) is the appropriate term here.

**Comment by jleung51** [comment]
Working on this in the branch `technologies-used`!

**Comment by daphne-chong** [comment]
Fixed in pull request #30
